server:
  port: 8080

spring:
  application:
    name: timedeal
  profiles:
    default: prod
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      image-folder: ${AWS_S3_IMAGE_NAME}
    cloudfront:
      cname: ${AWS_CLOUDFRONT_CNAME}
    stack:
      auto: false
    region:
      static: ${AWS_REGION}
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    sqs:
      queue-name: ${TIMEDEAL_TABLE_QUEUE_NAME}
    lambda:
      timedeal-update-arn: ${AWS_LAMBDA_TIMEDEAL_UPDATE_ARN}